### ISSUE TITLE
Stacktrace

### ISSUE THREAD

**Issue by Torrib** [dotKom/studlan#103]
Internal Server Error: /profile/update/
Traceback (most recent call last):
  File "/srv/www/studlan/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/www/studlan/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/www/studlan/studlan/apps/userprofile/views.py", line 36, in update_profile
    if form.is_valid():
  File "/srv/www/studlan/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 162, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/srv/www/studlan/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 154, in errors
    self.full_clean()
  File "/srv/www/studlan/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 354, in full_clean
    self._clean_form()
  File "/srv/www/studlan/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 378, in _clean_form
    cleaned_data = self.clean()
  File "/srv/www/studlan/studlan/apps/userprofile/forms.py", line 29, in clean
    nick = cleaned_data['nick']
UnboundLocalError: local variable 'cleaned_data' referenced before assignment

**Comment by melwil** [comment]
You have set cleaned_data inside the scope of an if, it needs to be declared in the scope of the clean() function.
